### ISSUE TITLE
AT commands Authorization google cloud

### ISSUE THREAD

**Issue by MATTYGILO** [googleapis/google-api-ruby-client#10989]
Hi I am using a sim800l to connect to the firebase Firestore server using the REST api. However, SIM800 doesn't use the REST api. It uses AT commands. How do I add the Authorization token to the data. I'm currently using this:

`AT+HTTPPARA="USERDATA","Authorization: Bearer [Token]"`

and get this error:

`ERROR\r\n`

How do I add the

**Comment by parthea** [comment]
The issue appears to be specific to the sim800l hardware. Regretfully, it's outside of the scope of this client library.  It would be best to reach out to the company that manufactures the sim800l hardware. I'm going to close this issue but please feel free to re-open it if you have an issue specific to this ruby library.

As an aside, bearing in mind that this is outside of my area of expertise, according to their documentation you can try to enable CME errors with verbose output using `AT+CMEE=2` . According to the documentation that will allow you to get verbose error information instead of just `ERROR`. You would want to send this command before you send the command that give you an error.  Another thing to consider is whether this module allows you to encrypt the information before sending tokens in clear text using AT commands.

![image](https://user-images.githubusercontent.com/5184014/179791240-8e790b19-6a38-42c8-894b-b20639c079d8.png)

![image](https://user-images.githubusercontent.com/5184014/179791640-d6fc2fc9-3607-46d2-bbc7-0e7e895b6fe0.png)
