### ISSUE TITLE
next_page method unexpected behaviour

### ISSUE THREAD

**Issue by monktools** [googleapis/google-api-ruby-client#155]
Hi,
i tested and searched a lot before write, but i have an issue with 'customsearch' api and next_page method.
When i make an api request like this 

``` ruby
response = client.execute(
:api_method => search.cse.list,
:parameters => {
 'q' => 'a query',
 'num' => 4,
 'cx' => 'MYCX'
 }
)
```

the result is ok, and the 'queries' => 'next_page' role have the 'startIndex' parameter correctly set to 5.
But if execute something like

`client.execute(response.next_page)` i get the same result of the first request like if the startIndex setted to 1. And `response.next_page` show me just the parameters of the first api request.

Is this a bug? Or probably a mistake of mine?

Thanks,
Andrea.

**Comment by Resisty** [comment]
In the hopes that somebody is still watching this, I've been googling for a few days and this is the closest I've come to finding an answer. I can't get my ruby script to return valid 'next page' results, even though there are supposedly 7000+ results and the first page shows only 10. I don't know what
`For custom search you need to handle this your self by looking at the next_page/previous_page roles in queries.`
means, because looking through queries yields:
`{"nextPage"=>[{"title"=>"Google Custom Search - quokka selfies", "totalResults"=>"7210", "searchTerms"=>"quokka selfies", "count"=>10, "startIndex"=>11, "inputEncoding"=>"utf8", "outputEncoding"=>"utf8", "safe"=>"off", "cx"=>"xxx", "fileType"=>"jpg", "searchType"=>"image"}], "request"=>[{"title"=>"Google Custom Search - quokka selfies", "totalResults"=>"7210", "searchTerms"=>"quokka selfies", "count"=>10, "startIndex"=>1, "inputEncoding"=>"utf8", "outputEncoding"=>"utf8", "safe"=>"off", "cx"=>"xxx", "fileType"=>"jpg", "searchType"=>"image"}]}`

and tossing either the nextPage[0] hash at the request parameters or just saying parameters['start-index'] = number both fail. What I have so far:

```
def gsearch(searchstr, ftype: 'jpg', start: nil, depth: nil)
  puts "Entering function with depth: \"#{depth}\""
  client = Google::APIClient.new(:application_name => 'IRC Bot Search Helper',
        :application_version => '0.0.1',
        :client_id => id,
        :client_secret => secret,
        :authorization => nil)
  search = client.discovered_api('customsearch')

  parameters = {
    'q' => searchstr,
    'key' => key,
    'cx' => cx,
    'searchType' => 'image',
    'fileType' => ftype
  }
  if start
    parameters['start-index'] = start
    parameters['max-results'] = 10
  end
  response = client.execute(
    :api_method => search.cse.list,
    :parameters => parameters
  )

  body = JSON.parse(response.body)
  #puts body['queries']
  if depth == nil
    depth = rand(5)
  end

  if body['queries'].has_key?('nextPage')
    tok = body['queries']['nextPage'][0]['startIndex']
  else
    tok = nil
  end

  if depth == 0 or !tok
    puts "Depth: #{depth}, returning body"
    return body
  end
  puts "Made it to the end, recursing with depth: #{depth}"
  return gsearch(search, start: tok, depth: depth - 1)
end
```

Obviously it doesn't work but for the life of me I have no idea why. Sorry for reopening an issue but this is the only place addressing it.

**Comment by sqrrrl** [comment]
Use parameters['start'], not parameters['start-index']

**Comment by Resisty** [comment]
Thanks for the reply! Updated my code/comment, but that doesn't work either.
