### ISSUE TITLE
Missing autoPricingMinPrice property in Google Merchant Product

### ISSUE THREAD

**Issue by fabn** [googleapis/google-api-ruby-client#19744]
The current version doesn't expose the property `autoPricingMinPrice` as documented in https://developers.google.com/shopping-content/reference/rest/v2.1/products#Product

**Comment by fabn** [comment]
Will likely solved by https://github.com/googleapis/google-api-ruby-client/pull/19599, is it possible to release it?

**Comment by dazuma** [comment]
That property is actually in the google-apis-content_v2_1 gem (which is not related to #19599). However, you're right, content v2.1 hasn't regenerated since November, and I'm not sure why. It looks like the [discovery document](https://github.com/googleapis/discovery-artifact-manager/blob/master/discoveries/content.v2.1.json) is up to date. Will have to investigate this.

**Comment by dazuma** [comment]
We determined why content v2.1 wasn't regenerating, and fixed the build process. https://rubygems.org/gems/google-apis-content_v2_1/versions/0.33.0 is now released and should have the property mentioned.
