### ISSUE TITLE
How to get all user list firebase auth?

### ISSUE THREAD

**Issue by mattandayo** [googleapis/google-api-ruby-client#2391]
I want to get the information of all users on Firebase Authentication.
Can I use this gem to get it?

**Comment by dazuma** [comment]
Unfortunately, we're not experts in how to use all the different APIs. This is just an open source project that generates client libraries based on the published service descriptions. I suggest consulting the [Firebase authentication documentation](https://firebase.google.com/docs/auth) and looking for an API call that will meet your needs. If you find an appropriate API and are not sure how it maps to methods in the gems, feel free to ask back here and we can help you understand how to find the appropriate method to call.

**Comment by mattandayo** [comment]
@dazuma 
Thanks for answering my question.
Sorry, I didn't explain my question well enough.

I know that this gem implements an interface to retrieve a specific user, and I believe that the get_account_info interface provided by this gem is the same as the getUser interface in the Firebase Admin SDK.

get_account_info: https://github.com/googleapis/google-api-ruby-client/blob/master/google-api-client/generated/google/apis/identitytoolkit_v3/service.rb#L207-L217
getUser: https://firebase.google.com/docs/auth/admin/manage-users?hl=ja#retrieve_user_data

Since this gem implements an interface like getUser in Firebase Admin SDK, I thought it also implements an interface similar to getUsers interface in Firebase Admin SDK, but I couldn't find it.
getUsers: https://firebase.google.com/docs/auth/admin/manage-users?hl=ja#bulk_retrieve_user_data

Do you know if an interface like getUsers has been implemented?

**Comment by dazuma** [comment]
This gem does not implement the Firebase Admin SDK. (Just because a call "looks similar" does not mean it is the same call.)

What I suggest is searching the Firebase documentation for a specific **REST API** call that matches the functionality you want. If you can find one, then we can probably find the corresponding method in one of these client gems. However, if there isn't a **REST API** call, then you'll need to use an actual Firebase Admin SDK (and I don't think one exists for Ruby).

**Comment by mattandayo** [comment]
@dazuma 
Thanks😃
