### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by Fl0p** [googleapis/google-api-ruby-client#2606]
with  
`gem.required_ruby_version = '>= 2.4'`
here
https://github.com/googleapis/google-api-ruby-client/blob/master/google-api-client/google-api-client.gemspec#L34

gem is not compatible with ruby 3.0.0
please do

`gem.required_ruby_version = '>= 2.4', '< 4'`

**Comment by dazuma** [comment]
This actually doesn't make sense to me. `gem.required_ruby_version = '>= 2.4'` should support Ruby 3.x just fine. I also just tested a couple of the clients against Ruby 3.0.0 and they seem to be working. Can you provide reproduction steps?

Also, please note the giant `google-api-client` gem is now considered deprecated and is no longer being maintained. Consider installing individual gems specific to the clients you are using (for example `google-apis-storage_v1`). You'll have a more pleasant install experience avoiding the 75mb all-in-one gem.

**Comment by Daniel-Reiling** [comment]
PREFACE: I am not a ruby developer nor do I know very much about it.

I wanted to add to this my experience today working with ruby and getting the below message:

```
➜  Thinkers-iOS git:(develop) ✗ bundle install  
Fetching gem metadata from https://rubygems.org/........
google-api-client-0.38.0 requires ruby version ~> 2.4, which is incompatible
with the current version, ruby 3.0.0p0
```

I use Ruby for iOS development and am tried upgrading to Ruby 3.0.0 using RVM.

I hope this helps if any.

**Comment by dazuma** [comment]
@Daniel-Reiling You are encountering this issue because you are using an old version (0.38.0) of the google-api-client library, which refuses to install on Ruby 3.0.0. Newer versions (0.44.2 and later) relax the requirement and allow installation on Ruby 3. Note: the newest version of the library is 0.53.0.

Try using `bundle update` to update all libraries in your bundle. If that fails to bring in a newer google-api-client, then it probably means one of your other dependencies is explicitly asking for an old version of google-api-client. You'll need to find out which one (the contents of your `Gemfile.lock` file should help you there), and get that dependency to update its requirements.

**Comment by Daniel-Reiling** [comment]
Thank you @dazuma! I very much appreciate your advice and will work on doing this. Sorry for the novice input :)

**Comment by Fl0p** [comment]
@dazuma Sure with 0.44.2 and later everything is fine


@Daniel-Reiling old version is required by fastlane
```
    fastlane (2.173.0)
      google-api-client (>= 0.37.0, < 0.39.0)

```
