### ISSUE TITLE
Caught error not in gzip format

### ISSUE THREAD

**Issue by marisveide** [googleapis/google-api-ruby-client#661]
Hi!

When using the google-api-client in plain ruby file, it works fine.

But as soon as I use it from Rails app, I get this error `Caught error not in gzip format`.

**The debug log looks like this:**
```log
D, [2018-04-02T12:31:47.149932 #17520] DEBUG -- : Sending HTTP get https://www.googleapis.com/drive/v2/files?fields=nextPageToken%2C%20items%28%2A%29&q=%27root%27%20in%20parents&spaces=drive
D, [2018-04-02T12:31:47.202377 #17520] DEBUG -- : [httplog] Sending: POST https://www.googleapis.com/oauth2/v3/token
D, [2018-04-02T12:31:47.202739 #17520] DEBUG -- : [httplog] Data: grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJleGNlbGlmeS1hcHBAZXhjZWxpZnktaW8uaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjMvdG9rZW4iLCJleHAiOjE1MjI2NjE1NjcsImlhdCI6MTUyMjY2MTQ0Nywic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2RyaXZlIn0.iMyXxO49bxBl-xRxsDF3Hmj7Wkl2lIfuOf4yrNq7UABPnzEriAjdD92X6qTbmGXClOOdAHhbxySQ2ZO6nxVOsTucuF2-WOyQHZcNZxWgnZ5i62qfaUR3M8rzUn4jwWEjbyTGvDiV0NoyEXFja1iSoPdbjE8EU_ONg1G9R7qzJNkMl0Wpg7RxTepWBNfZv9cNysXpVwtFxqez3YmGdGl93kzWTbbaBs0xuhvom_Yu1uBO_lX2Un0Vlih69d5f3WcsunDkQf3Z_jtHv0ZK-2aOvxnLIimMummMyyrn1sBIouc7FNsZKOSLMqTUsL9WJyHetOJZKsY4er9yXY33xzRI_A
D, [2018-04-02T12:31:47.203579 #17520] DEBUG -- : [httplog] Connecting: www.googleapis.com:443
D, [2018-04-02T12:31:47.815840 #17520] DEBUG -- : [httplog] Status: 200
D, [2018-04-02T12:31:47.816152 #17520] DEBUG -- : [httplog] Benchmark: 0.612795 seconds
D, [2018-04-02T12:31:47.816671 #17520] DEBUG -- : Caught error not in gzip format
D, [2018-04-02T12:31:47.817137 #17520] DEBUG -- : Error - #<Zlib::GzipFile::Error: not in gzip format, input="{\n \"access_token\": \"ya29.c.ElmRBS-MRbG48N2boi6f-S6b54eXd7Tv-29_Wa1VBUsz4f4XfnLjd3rYDlciKuzmieU7fGAUDTypOFXF2K_z_Wulw7OtGRiCu1iHU-chn-9TqdQkXZytrW5AUA\",\n \"token_type\": \"Bearer\",\n \"expires_in\": 3600\n}\n">
```

**My Gemfile is like this:**
```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'httparty'
gem 'sinatra'
gem 'rack', github: 'rack/rack'
gem 'rack-protection', github: 'sinatra/sinatra'
gem 'sidekiq'

gem 'rubyzip', '~> 1.2.1'
gem 'axlsx', :git => 'https://github.com/marisveide/axlsx.git'
gem 'roo', '~>2.7.1'
gem 'roo-xls'
gem 'paperclip'
gem 'paper_trail'
gem 'htmlentities'
gem 'translit'

gem 'vuejs-rails'
gem 'momentjs-rails'
gem 'dropzonejs-rails'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'lodash-rails'
gem 'popper_js', '~> 1.12.5'
gem 'browser'
gem 'addressable'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'shopify_app', '~> 7.2.10'
gem 'shopify_api', '~> 4.9.0'
gem 'omniauth-shopify-oauth2', '~> 1.1.17'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

gem 'aws-sdk'
gem 'rack-tracker'
gem 'filesize'
gem 'slack-notifier'
gem 'spawnling', '~> 2.1' # Process spawner
gem 'crono'
gem 'daemons'
gem 'nokogiri'
# gem 'faraday', '0.9.1'
gem 'google-api-client'

gem 'affiliate', path: 'engines/affiliate'

group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails', ">= 2.0.0.beta"
  gem 'rspec'
  gem 'webmock'
  gem 'factory_bot_rails'
  gem 'simplecov', :require => false
  gem 'rubocop'
  gem 'diffy'
  gem 'vcr' # Records real HTTP responses from web, and then stubs them
  gem 'httplog'
end

group :test do
  gem 'database_cleaner'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'debugger-ruby_core_source'
  gem 'derailed'
  gem 'rerun'
end
```

I tried to pin the faraday version to 0.9.1 (uninstalled the 0.9.2 version), but that still doesn't solve the issue. (ref to this issue: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/367)

I understand that this might be due to some other gem, because it works with plain ruby script, but cannot find what might be causing this issue.

Please, help - how to make Google API work in Ruby app?

Thanks!

Maris

**Comment by mattwhisenhunt** [comment]
What version of google-api-client is installed?

**Comment by marisveide** [comment]
From Gemfile.lock:

```
    google-api-client (0.20.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.7.0)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
```

I found that basically it was failing inside the httplog, because the header is sent as type/gzip, but contains already unzipped content. 
So it looks like as if google-api-client (or some other component in the chain) is unzipping that content but is not updating the header mime type.

**Comment by mattwhisenhunt** [comment]
I'm a bit out of my depth here in Ruby-land so bear with me: typically these api-client libraries don't pass along responses but instead turn the raw http responses into the data types found in the generated directory. It sounds like you have a middleware stack set up that is using google-api-client as one layer in that, is that correct?

**Comment by marisveide** [comment]
I found that you might be right - it might be that the rspec is unzipping the body because this just happens when I run the request from the rspec.
I have created an issue for the rspec gem (https://github.com/rspec/rspec/issues/28), let's see what they will say.

**Comment by marisveide** [comment]
Appears that this has nothing to do with rspec.

I have created here the fresh Rails project that reproduces that issue:
https://github.com/marisveide/reproduce-gzip-error-in-httplog

**Comment by turley** [comment]
This seems to be a recurring issue with a lot of http libraries (at least in Ruby) right now. It boils down to the libraries being configured to automatically decompress responses with gzip encoding *while keeping the `Content-Encoding` header intact*.

Ruby's built-in `Net::HTTP` does this correctly (removes the `Content-Encoding` header when it decompresses the response), but some libraries do not, including em-http-request and httpclient (https://github.com/nahi/httpclient/blob/e13cd048e5d0c94bbc1556815081c4cc87b77400/lib/httpclient/session.rb#L702).

So you have higher-level HTTP clients seeing a response with a header that indicates the body is still compressed (in this case it's httplog here: https://github.com/trusche/httplog/blob/b1b4a77b564fb95876f3d3c760016986ad1c6af1/lib/httplog/http_log.rb#L82 failing because httpclient already decoded the body without updating the `Content-Encoding` header). The same thing used to happen in google-api-ruby-client until they stripped out any attempt to decompress responses in favor of making the `transparent_gzip_decompression` client option enabled by default.

My opinion (see https://github.com/igrigorik/em-http-request/pull/270#issuecomment-42115196) is that http client libraries should be consistent; if you decompress the body, you need to update the response headers to match what you've done. Unfortunately not everyone agrees with that, so we'll likely keep seeing these issues pop up.

**Comment by blowmage** [comment]
Seeing as this error originated in httplog due to this library's use of HTTPClient's `transparent_gzip_decompression` feature, and httplog issued a fix for this, I am inclined to close this issue and ask that users update httplog to at least version 1.0.3. I don't anticipate this library will move away from HTTPClient or its `transparent_gzip_decompression` feature anytime soon.
