### ISSUE TITLE
Google::Apis::AnalyticsV3::GaData#rows should be empty Array when no results, not nil

### ISSUE THREAD

**Issue by JasonBarnabe** [googleapis/google-api-ruby-client#675]
```ruby
    @api_service.get_ga_data(
      "ga:#{profile_id}",
      start_date.strftime("%Y-%m-%d"),
      end_date.strftime("%Y-%m-%d"),
      'ga:sessions,ga:transactionRevenue',
      sampling_level: "HIGHER_PRECISION",
      dimensions: "",
      sort: "-ga:sessions"
    ) do |transaction_data, exception|
      raise exception if exception
      return transaction_data.rows[0]
    end
```

This raises on `transaction_data.rows[0]` when there are no results as `transaction_data.rows` is `nil`. For consistency, this should be an empty `Array`.

**Comment by dazuma** [comment]
The core reporting API appears to omit the rows field when there are no results. It might be possible to translate this to an empty collection if the field is known to have a collection type, but I'm not convinced we should be doing this across all such cases. (This could be a breaking change and have other unknown side effects.) I'm turning this into a feature request for further investigation. If the blast radius turns out to be smaller than I suspect it is, then maybe it's reasonable to do, but I wouldn't hold my breath.

**Comment by bajajneha27** [comment]
Hi @JasonBarnabe 
Appreciate your patience here. Unfortunately, we're not taking any significant feature requests for google-api-ruby-client and hence we won't be able to make this change. I'll go ahead and close this issue. Thank you!
