### ISSUE TITLE
Will there be support for Google AutoML?

### ISSUE THREAD

**Issue by echan00** [googleapis/google-api-ruby-client#721]
Is there something I can use in the meantime until Google AutoML is supported by this library?

I also looked at at the [Ruby Google Auth Library](https://github.com/googleapis/google-auth-library-ruby), but it looks like the [scope for AutoML](https://developers.google.com/identity/protocols/googlescopes) doesn't exist...

**Comment by danlewis** [comment]
The following works for me until they add support for AutoML. Note that Service Account credentials needs to be setup first. Hope it helps.

```
access_token=Google::Auth.get_application_default(["https://www.googleapis.com/auth/cloud-platform"]).fetch_access_token!["access_token"]

conn = Faraday.new(url: "https://automl.googleapis.com", headers: {"Authorization" => "Bearer #{access_token}", "Content-Type" => "application/json" })

response=conn.post "/v1beta1/projects/YOUR_PROJECT_PATH....", {payload: {textSnippet: {content: "YOUR TEXT HERE", mime_type: "text/plain"}}}.to_json
```

**Comment by quartzmo** [comment]
This question has also been asked for Google Cloud Ruby in googleapis/google-cloud-ruby#2491.

**Comment by dazuma** [comment]
The AutoML team has not yet released their discovery document into the discovery service, probably because the service is still in limited beta. We will likely be producing an AutoML client as part of the https://github.com/googleapis/google-cloud-ruby repository during Q1 of 2019. That will probably be your best bet when it is complete, as those clients are generally higher quality than this gem.

In the meantime, you can always make raw HTTP requests as danlewis points out. It may also be possible to download the discovery document yourself, and use the tools in this gem to generate your own client. (See the README for details.)
