### ISSUE TITLE
MIME type error when upload App Bundle

### ISSUE THREAD

**Issue by espadandy** [googleapis/google-api-ruby-client#775]
Our company PTC is using the Ruby package called AndroidPublisherService to upload App Bundle to Google Play Store. This is the link to the docs:
https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/AndroidpublisherV2/AndroidPublisherService#upload_edit_bundle-instance_method

We used to deliver APKs for years without any issue. Currently we changed the delivered package from .apk to .aab, cancelled the optimization for the APK (because we use bundle already which I didn't see it needs to be optimized) and use AndroidPublisher::upload_edit_bundle function. It will return the error:
"/home/go/.gem/ruby/2.3/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:228:in `check_status': badContent: Media type 'application/x-authorware-bin' is not supported. Valid media types: [application/octet-stream] (Google::Apis::ClientError)"

I searched for "Media type" (which is also called MIME type), and found application/x-authorware-bin is exactly .aab file's MIME type, so it should be supported by nature. application/octet-stream is the MIME type of .bin file which is not related to Google Play Store at all. I'm not sure how to fix this issue. Can you give me some help?

**Comment by blowmage** [comment]
It looks to me that this error is coming from the API. Are you setting the content type manually? What happens if you leave content type unspecified or set it to "application/octet-stream" per the API's error message? (The "application/octet-stream" is the default content type for a generic binary file.)

Can you post a simple reproduction example and the entire error backtrace?

**Comment by markrcote** [comment]
I ran into this too calling `upload_edit_bundle` without specifying `content_type`. Adding                 `content_type: "application/octet-stream"` to the call fixed it. It appears that, if it is not specified, the API client must be looking up the default mimetype associated with `.aab` files, which is currently `application/x-authorware-bin` on many (most? all?) systems. Given this, I think the API client should be specifying it so that the caller doesn't have to, as this is unexpected behaviour for a default option.

**Comment by blowmage** [comment]
Thanks for the verification, @markrcote!

**Comment by markrcote** [comment]
Does this mean the default value for `content_type` will be fixed?

**Comment by blowmage** [comment]
It means that there are several ways to resolve this. First, you have the option set the `application/octet-stream` content type on the upload, per API's the error's message. Second, you could change your file's extension to one that does not have a known mime type, e.g. `filename.appbundle`. Third, you can update the mime type registration and remove the `aab` extension:

```ruby
require "mime/types"

# Remove .aab mime type registration
types = MIME::Types.of("file.aab")
types.each do |type|
  type.extensions -= ["aab"]
end

# do the upload
```

**Comment by markrcote** [comment]
Yes, it is easy enough to workaround. Considering this is the official Ruby client for the Play Store API, though, I personally would have expected the defaults to work, considering `.aab` is, as far as I can tell, the official file extension for Android App Bundles.
