### ISSUE TITLE
Cloud Video Intelligence API Method: operations.get

### ISSUE THREAD

**Issue by avokhmin** [googleapis/google-api-ruby-client#808]
Hello.

Why did you remove `Google::Apis::VideointelligenceV1::CloudVideoIntelligenceService#get_operation` method?

See:

- [API docs](https://cloud.google.com/video-intelligence/docs/reference/rest/v1/operations/get)
- [commit](https://github.com/googleapis/google-api-ruby-client/commit/aeb54f610d58ad559d9fec1fba7f0ec5232831c6#diff-42b7e6de1bd34e865c2d0ad47f3a3f54L146)

#### Environment details

  - OS:
  - Ruby version:
  - Gem name and version: `google-api-client (0.30.6)`

#### Steps to reproduce

  1. install `google-api-client (0.30.6)`
  2. see `Code example`

#### Code example

```ruby
client = Google::Apis::VideointelligenceV1::CloudVideoIntelligenceService.new
client.key = 'foo-bar'
client.get_operation 'name'
```

**Comment by blowmage** [comment]
This gem is generated using the [Google Discovery service](https://developers.google.com/discovery/). So the simple answer is that this was changed because the Visual Intelligence discovery document was changed. And the obvious next question is why was it changed and what should users too. @dazuma do you have an insight into this change?

**Comment by avokhmin** [comment]
we can use `#get_operation_project_location_operation` instead of `#get_operation`
